### ISSUE TITLE
Crash after loading theme a second time. 

### ISSUE THREAD

**Issue by adrot** [usagirei/3DS-Theme-Editor#12]
Worked first time. Also, the smdh doesn't seem to work after making the modifications in Usagi.

NAudio.MmException: BadDeviceId calling waveOutOpen
   en NAudio.Wave.WaveOut.Init(IWaveProvider waveProvider)
   en ThemeEditor.WPF.AudioPlayer.SetAudioData(Byte[] wavData) en D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\AudioPlayer.cs:línea 81
   en ThemeEditor.WPF.MainWindow.LoadBGM_PostExecute(LoadBGMResults result) en D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\MainWindow.BGM.cs:línea 17
   en ThemeEditor.WPF.RelayCommandAsync`1.<Execute>d__11.MoveNext() en D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\RelayCommand.cs:línea 0
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   en System.Windows.Threading

**Comment by usagirei** [comment]
Check if you have an audio device available (and plugged cords to a speaker/headphone)

**Comment by adrot** [comment]
Thx. Fixed it.
