### ISSUE TITLE
Bug quando vou procurar uma imagem

### ISSUE THREAD

**Issue by SaySayTakamura** [usagirei/3DS-Theme-Editor#15]
Hey amigo, fui tentar esse editor porém quando eu vou na aba de imagem e clico em importar imagem não acontece nada.

**Comment by usagirei** [comment]
Defina não acontece nada. 
Nao aparece nem o dialogo de procurar arquivo?

**Comment by SaySayTakamura** [comment]
não abre aquela caixinha de escolher o arquivo (e pelo tutorial do mano jobs antes de abrir a caixinha pra escolher o arquivo mostraria a seguinte frase seguida de uma barra de load "Escolhendo arquivo" nem isso aparece) nenhuma das opções para selecionar um arquivo funfa.

**Comment by SaySayTakamura** [comment]
eu aperto em importar imagem e aparece uma caixinha (como citada acima) escrito "escolhendo arquivo" e uma barra de load em baixo porém essa caixinha só aparece por misero segundo e some sem abrir algo pra eu selecionar um arquivo nem nada.

Já reinstalei o .net e nada.

**Comment by usagirei** [comment]
Não imagino porque nao está abrindo os dialogos, porém, tenta arrastar e soltar a imagem nos icones que tem em cima do preview (do explorer pra dentro do editor). É pra ter a mesma função do dialogo, mas sem o dialogo em sí. 

Clicar nos botões em cima do preview é pra abrir o dialogo também, mas acho que se nao está funcionando um nao vai abrir pelo outro.

**Comment by SaySayTakamura** [comment]
cara uma pergunta, quando você diz que o WPF não suporta mono, isso serve para um troço chamado GTK# for .NET?

**Comment by usagirei** [comment]
Wpf so funciona em Windows infelizmente, usa directx como backend, reescrever o projeto inteiro com outro framework de UI cross-platform ia ser um trabalho do cão que eu não tenho tempo pra dedicar. Talvez um dia quando Avalonia ficar mais maduro e tal
