### ISSUE TITLE
application crashes with ArgumentNullException

### ISSUE THREAD

**Issue by neumaennl** [usagirei/3DS-Theme-Editor#3]
System.ArgumentNullException: model
Parametername: Model Can't be null
   bei ThemeEditor.WPF.Themes.ViewModelBase..ctor(Object model, String tag) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\Themes\ViewModelBase.cs:Zeile 51.
   bei ThemeEditor.WPF.Themes.TexturesViewModel..ctor(Textures model, String tag) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\Themes\TexturesViewModel.cs:Zeile 35.
   bei ThemeEditor.WPF.Themes.ThemeViewModel..ctor(Theme model) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\Themes\ThemeViewModel.cs:Zeile 31.
   bei ThemeEditor.WPF.MainWindow.LoadTheme_PostExecute(LoadThemeResults result) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\MainWindow.Themes.cs:Zeile 226.
   bei ThemeEditor.WPF.RelayCommandAsync`2.<Execute>d__11.MoveNext() in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\RelayCommand.cs:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

happens when trying to open this theme: https://mega.nz/#F!HQVX0IwC!IfdjNFFMsbWEfxE31UskIA!yIdgybZb

**Comment by usagirei** [comment]
Should be fixed in the [1.0.6.5](https://github.com/usagirei/3DS-Theme-Editor/releases/tag/v1.0.6.5) Release.

Thanks for the feedback!

**Comment by neumaennl** [comment]
now it just resarts. I still can't open that theme :neutral_face: 
okay, on the 2nd try it worked.
weird.
But thanks for fixing it so fast! :-)
