### ISSUE TITLE
Wrong colors on the bottom screen buttons and wrong opacity on the labels on the top screen

### ISSUE THREAD

**Issue by internetakias** [usagirei/3DS-Theme-Editor#5]
Seems like my GBATemp post was ignored so I'll leave this here
![usagicomp](https://cloud.githubusercontent.com/assets/5077063/14312741/4ab5c0e2-fbf6-11e5-82bf-fc4e4f971f2e.png)

**Comment by usagirei** [comment]
Did you try it in the latest version (The bottom screen pressed state)?

EDIT: Nvm, it's still swapped, and there was another bug with it still
Also which theme is that so i can base the top opacity off

**Comment by internetakias** [comment]
<a href="https://www.youtube.com/watch?v=78NFdJTuRqg">1st Day from Devil Survivor Overclocked</a>

**Comment by usagirei** [comment]
Are you able to compile from source and check if the latest commit (61144ce) is more accurate?

**Comment by internetakias** [comment]
Better but still inaccurate, probably because Button Top does nothing now. 
![devilsurvivor](https://cloud.githubusercontent.com/assets/5077063/14365768/1888eefa-fd18-11e5-84cf-1dc3c0973367.png)
Here's the theme, by the way. In case you weren't able to find it on your own: https://my.mixtape.moe/naoziw.7z

**Comment by usagirei** [comment]
What do you mean by Button Top does nothing now?

**Comment by internetakias** [comment]
as in it doesn't affect the color of the pressed button in any way, even though it's probably responsible for the vignette-like effect on the pressed button

**Comment by usagirei** [comment]
Fair enough, it was actually Bottom Color that composes a VERY TINY  amount of the Glow color on the top when pressed. Commit ebeebdf should have it now, along the non-pressed white tint (Only visible on darker colors), if you would give it a try

**Comment by internetakias** [comment]
https://my.mixtape.moe/zqoqfi.png
https://my.mixtape.moe/bkdjyw.png
Looks better but the unpressed buttons aren't the same color throughout now for some reason
Also, you seem to have give a simple gradient to the pressed button when it seems to be more like the diamond gradient in photoshop

**Comment by usagirei** [comment]
Sorry but I work with what tools i have at my disposal, I also can't see where a diamond shape gradient comes in. It's supposed to be a _preview_, not a 1:1 render of the console unit.

It's close enough to give a good representation of the final output. Mind you it's being rendered on a completely different platform, with a completely different toolset, and we don't have access to the home menu render pipeline either way to get a better feel of it.

The colors have been fixed and the opacity reduced, so I'll be closing this issue.
