### ISSUE TITLE
Regression: Bottom Screen Corner Buttons look brighter than they're supposed to now

### ISSUE THREAD

**Issue by internetakias** [usagirei/3DS-Theme-Editor#6]
Sorry for going out on a tangent in the other issue but I noticed that after the latest update, the bottom screen buttons have a square inside them now that's brighter than the rest of the button for some reason
![usagicomp](https://cloud.githubusercontent.com/assets/5077063/14413985/cde7d474-ff92-11e5-9986-035a15044dca.png)
By the way, you might know this already, but I just noticed that the corner buttons are very slightly transparent.

**Comment by usagirei** [comment]
It's kind of hard to match the actual value, but that white glow is present when the button is not pressed.
You can verify this by sending a theme with a full-black top corner button colors (just tick the flag and send it over).
I'll reduce the opacity a bit more (it was at 39 as of now, let's try 19) - 74a9cca

**Comment by internetakias** [comment]
![usagiblack](https://cloud.githubusercontent.com/assets/5077063/14414824/bc3eaaf0-ffa0-11e5-89cf-a3519507cd73.png)
I see what you mean

**Comment by usagirei** [comment]
The image above was with 1.0.8.2 or 74a9cca?

**Comment by internetakias** [comment]
1.0.8.2
I'll compile the new commit soon and report back

**Comment by internetakias** [comment]
https://my.mixtape.moe/yizcab.png

**Comment by usagirei** [comment]
Seems about right now, if not the 3DS is a bit more visible still

**Comment by internetakias** [comment]
3DS also looks more like a gradient that's part of the main button, rather than a square inside it, but maybe you can't recreate that.

**Comment by usagirei** [comment]
As of d6b273d (v1.0.8.3) these changes are on the released build, it misses a bit of the gradient (which i may tweak later on) but the opacity has been reduced
