### ISSUE TITLE
White Gradient option doesn't show up on a real 3DS

### ISSUE THREAD

**Issue by SonoSooS** [usagirei/3DS-Theme-Editor#8]
On a real 3DS the top screen shows up as if the White Gradient option were turned off, like if the White Gradient option wasn't working at all.

If I re-save the file in YATA+, then the black-effect goes away, but the colors are different than in the preview (on a real 3DS the color is much brighter, and less saturated).

When I open both the one exported with this, and the one exported with YATA+, they look the same in the preview window, but they look different on a real 3DS.

I have uploaded [body_LZ.zip](https://github.com/usagirei/3DS-Theme-Editor/files/352243/body_LZ.zip), so you can inspect if this problem is in the file or it's a bug in the saving process.
body_LZ.bin is the one exported with this, and body_LZ_yataplus.bin is exported with YATA+

**Comment by usagirei** [comment]
I'm aware, i've fixed it already in my private builds, i'll release a new version with some new stuff i've been working on soon-ish

**Comment by usagirei** [comment]
latest release should have this fixed.

**Comment by SonoSooS** [comment]
Thanks, it works now :D

But weirdly, now the problem is the same: the preview isn't accurate regarding what the 3DS actually displays. While the preview displays nice saturated colors, on the 3DS it's barely saturated at all. This only applies to the top screen in "Solid color and Texture" mode. For example, I set the background color to "#FF197A38", gradient 0.2, main opacity 1.0, alt opacity 0.0, gradient color 1.0, the preview displays a nice little-bit-bright green color, while on the 3DS it's barely noticatble that it actually contains green color (it's more of a grayish-white).

**Comment by usagirei** [comment]
That's a mix of 3DS LCD characteristics of how it displays colors, and of me not having acess to exactly how it works.
I try my best at an approximation, but that's it, an approximation.

**Comment by SonoSooS** [comment]
Ohh, okay then. Thanks anyways :D
